version: 2.1

executors:
  rill-env-linux:
    docker:
      - image: yutopp/rill-build-env:x86_64-unknown-linux-gnu_llvm10_latest

jobs:
  build_and_push_llvm_image:
    docker:
      - image: circleci/buildpack-deps:stable
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.9-ce
      - run:
          working_directory: ~/repo/dockerfiles
          command: ./build.llvm10.sh

  build_and_push_env_image:
    docker:
      - image: circleci/buildpack-deps:stable
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.9-ce
      - run:
          working_directory: ~/repo/dockerfiles
          command: ./build.sh

  build-and-test:
    executor: rill-env-linux
    working_directory: ~/repo
    steps:
      - checkout
      - run: eval $(opam env)
      - run: opam update
      - run: mkdir build
      - run:
          command: cmake ..
          working_directory: ~/repo/build
      - run:
          command: make rillc-init
          working_directory: ~/repo/build
      - run:
          command: make
          working_directory: ~/repo/build

workflows:
  version: 2.1
  build:
    jobs:
      - build_and_push_llvm_image:
          filters:
            tags:
              only: /^docker-llvm.*/
      - build_and_push_env_image:
          filters:
            tags:
              only: /^docker-env.*/
      - build-and-test
