version: 2.1

jobs:
  build-and-test:
    docker:
      - image: yutopp/rill-build-env:base-x86_64
    steps:
      - checkout

      - restore_cache:
          keys:
            - opam-cache-v1-{{ arch }}-{{ checksum "rillc/rillc.opam.locked" }}
            - opam-cache-

      - run:
          working_directory: rillc
          command: |
            opam switch create . 4.10.0
            opam repo add rillc-deps-opam-repo https://github.com/yutopp/rillc-deps-opam-repo.git
            opam update
            opam install . --deps-only --with-test -y --locked

      - save_cache:
          key: opam-cache-v1-{{ arch }}-{{ checksum "rillc/rillc.opam.locked" }}
          paths:
            - ~/repo/rillc/_opam

workflows:
  version: 2.1
  build:
    jobs:
      - build-and-test
