version: 2.1

jobs:
  build_and_test:
    docker:
      - image: yutopp/rill-build-env:base-x86_64
    steps:
      - checkout

      - run:
          working_directory: rillc
          command: |
            opam switch create . --empty -y

      - restore_cache:
          keys:
            - opam-cache-v1-{{ arch }}-{{ checksum "rillc/rillc.opam.locked" }}
            - opam-cache-

      - run:
          working_directory: rillc
          command: |
            opam repo add rillc-deps-opam-repo https://github.com/yutopp/rillc-deps-opam-repo.git

      - run:
          working_directory: rillc
          command: |
            opam update

      - run:
          working_directory: rillc
          command: |
            opam install . --deps-only --with-test -y --locked -j "$(nproc)"

      - save_cache:
          key: opam-cache-v1-{{ arch }}-{{ checksum "rillc/rillc.opam.locked" }}
          paths:
            - ~/repo/rillc/_opam

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build_and_test
