name: CI

on: [push]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    container:
      image: yutopp/rill-build-env:base-x86_64

    env:
      OPAMROOT: /root/.opam

    steps:
      - uses: actions/checkout@v2

      - run: |
          apt-get update -y -qq && apt-get install -y -qq nodejs

      - name: Cache multiple paths
        id: cache-opam
        uses: actions/cache@v2
        with:
          path: |
            /root/.opam
          key: ${{ runner.os }}-${{ hashFiles('rillc/rillc.opam.locked') }}

      - working-directory: rillc
        run: |
          opam repo add rillc-deps-opam-repo https://github.com/yutopp/rillc-deps-opam-repo.git

      - working-directory: rillc
        run: opam update

      - working-directory: rillc
        run: opam install . --deps-only --no-depexts --with-test -y --locked -j "$(nproc)"

      - working-directory: rillc
        run: make build

      - working-directory: rillc
        run: make test

      - run: |
          cmake -B build \
                -DRILL_TARGET_TRIPLES=x86_64-unknown-linux-gnu

      - working-directory: build
        run: make

      - working-directory: build
        run: make CTEST_OUTPUT_ON_FAILURE=1 test

      - run: cmake --install build --prefix /usr/local/rill-ci
