name: Meta Push LLVM Image

on: [push]

jobs:
  buildAndPush:
    strategy:
      matrix:
        host: ["x86_64"]
        llvm-version: ["11.0.0"]
    runs-on: ubuntu-20.04
    env:
      DOCKER_IMAGE_NAME: "yutopp/rill-build-env"
      DOCKER_IMAGE_TAG: "llvm-${{ matrix.llvm-version }}-${{ matrix.host }}"
    steps:
      - id: check-image-existence
        run: |
          result="$(docker image inspect ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} 2> /dev/null || true)"
          if [ "$result" = "[]" ]; then
            echo "::set-output name=exists::false"
          fi

      - uses: actions/checkout@v2

      - id: build-and-push-image
        if: steps.check-image-existence.outputs.exists == 'false'
        working-directory: dockerfiles/meta
        env:
          LLVM_VERSION: "${{ matrix.llvm-version }}"
        run: |
          docker build --rm -t "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}" \
                       --build-arg LLVM_VERSION="${LLVM_VERSION}" \
                       -f Dockerfile.llvm .
          docker push "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
